# Generated by Django 3.0.6 on 2020-06-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userprofileinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
